# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hyperpublic"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["etang"]
  s.date = "2011-10-19"
  s.description = "Provides easy access to the hyperpublic api"
  s.email = "etang@hyperpublic.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/hyperpublic.rb",
    "lib/hyperpublic/all.rb",
    "lib/hyperpublic/base.rb",
    "lib/hyperpublic/categories.rb",
    "lib/hyperpublic/oauth.rb",
    "lib/hyperpublic/offers.rb",
    "lib/hyperpublic/people.rb",
    "lib/hyperpublic/places.rb",
    "lib/hyperpublic/request.rb",
    "lib/hyperpublic/things.rb",
    "lib/hyperpublic/version.rb",
    "spec/hyperpublic/base_spec.rb",
    "spec/hyperpublic/people_spec.rb",
    "spec/hyperpublic/places_spec.rb",
    "spec/hyperpublic/request_spec.rb",
    "spec/hyperpublic/things_spec.rb",
    "spec/hyperpublic_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/hyperpublic/hyperpublic_ruby"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Client library for the hyperpublic api"
  s.test_files = [
    "spec/hyperpublic/base_spec.rb",
    "spec/hyperpublic/people_spec.rb",
    "spec/hyperpublic/places_spec.rb",
    "spec/hyperpublic/request_spec.rb",
    "spec/hyperpublic/things_spec.rb",
    "spec/hyperpublic_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_runtime_dependency(%q<hashie>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<httparty>, ["~> 0.7.8"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.5.1"])
      s.add_runtime_dependency(%q<multi_json>, ["~> 1.0.3"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<fakeweb>, ["~> 1.3.0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_runtime_dependency(%q<oauth>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.2.1"])
      s.add_development_dependency(%q<autotest-growl>, [">= 0"])
      s.add_development_dependency(%q<ZenTest>, [">= 4.6.2"])
    else
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<hashie>, ["~> 1.1.0"])
      s.add_dependency(%q<httparty>, ["~> 0.7.8"])
      s.add_dependency(%q<rest-client>, ["~> 1.5.1"])
      s.add_dependency(%q<multi_json>, ["~> 1.0.3"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<fakeweb>, ["~> 1.3.0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<oauth>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.2.1"])
      s.add_dependency(%q<autotest-growl>, [">= 0"])
      s.add_dependency(%q<ZenTest>, [">= 4.6.2"])
    end
  else
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<hashie>, ["~> 1.1.0"])
    s.add_dependency(%q<httparty>, ["~> 0.7.8"])
    s.add_dependency(%q<rest-client>, ["~> 1.5.1"])
    s.add_dependency(%q<multi_json>, ["~> 1.0.3"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<fakeweb>, ["~> 1.3.0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<oauth>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.2.1"])
    s.add_dependency(%q<autotest-growl>, [">= 0"])
    s.add_dependency(%q<ZenTest>, [">= 4.6.2"])
  end
end

